//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastLearning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClaseUsuario
    {
        public int id_clase { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> calificacion_alumno { get; set; }
        public Nullable<int> calificacion_profesor { get; set; }
        public Nullable<int> id_pago { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
