//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastLearning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.ClaseUsuario = new HashSet<ClaseUsuario>();
        }

        public int id { get; set; }
        public int id_habilidad { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string lugar { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string dia { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.TimeSpan hora_inicial { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.TimeSpan hora_final { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.DateTime fecha_inicial { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.DateTime fecha_final { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [Range(1, 300, ErrorMessage = "Precio entre 1 y  300")]
        public decimal precio { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        [Range(1, 50, ErrorMessage = "Vacantes entre 1 y 50")]
        public int vacantes { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public int id_estado { get; set; }

        public virtual Estado Estado { get; set; }
        public virtual Habilidad Habilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaseUsuario> ClaseUsuario { get; set; }
    }
}
