//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habilidad()
        {
            this.Clase = new HashSet<Clase>();
        }
    
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_tema { get; set; }
        public int id_nivel { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase> Clase { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual Tema Tema { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
