//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastLearning.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SolicitudUsuario
    {
        public int id_solicitud { get; set; }
        public int id_usuario { get; set; }
        [Required(ErrorMessage = "Campo obligatorio")]
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }

        public virtual Solicitud Solicitud { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
